# Generated by Django 2.2.5 on 2019-10-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0003_auto_20191011_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
