# Generated by Django 2.2.5 on 2019-10-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('znahar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='uuid',
            field=models.CharField(default='000000', max_length=32, unique=True),
        ),
    ]
