# Generated by Django 2.2.5 on 2019-10-29 08:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('znahar', '0003_warehouse_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='image',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
