# Generated by Django 2.2.5 on 2019-11-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('znahar', '0004_auto_20191029_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
