# Generated by Django 2.2.5 on 2019-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('znahar', '0006_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
