# Generated by Django 2.2.5 on 2019-11-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('znahar', '0007_jobs_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(),
        ),
    ]
