# Generated by Django 2.2.5 on 2019-11-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('znahar', '0008_auto_20191112_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='longtitude',
            field=models.FloatField(null=True),
        ),
    ]
