# Generated by Django 2.2.5 on 2020-04-24 11:12

from django.db import migrations, models
import znahar.models


class Migration(migrations.Migration):

    dependencies = [
        ('znahar', '0009_auto_20191127_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autosuggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=znahar.models.upload_file)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
