# Generated by Django 2.2.5 on 2020-05-05 10:11

from django.db import migrations, models


def add_default_vnames(apps, schema_editor):
    Promotion = apps.get_model('promotions', 'Promotion')
    for promotion in Promotion.objects.all():
        promotion.visible_name = promotion.title
        promotion.save()


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20200422_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='visible_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(add_default_vnames, lambda x,y:None),
    ]
